### ISSUE TITLE
"Unauthenticated."

### ISSUE THREAD

**Issue by MSufianS** [training-yoyosan/example-backend#2]
Hi,

I try to login but get "Unauthenticated." error.

Ubuntu Nginx

Thanks

**Comment by yoyosan** [comment]
Hey.

Are you talking about a local setup?

Can you attach some pictures from the browser Console and XHR request tabs?

**Comment by MSufianS** [comment]
Hi yoyosan,

After I read carefully on readme is solve my problem...
Sorry about that.

Thanks...

**Comment by AO-IO** [comment]
> Hi yoyosan,
> 
> After I read carefully on readme is solve my problem...
> Sorry about that.
> 
> Thanks...

Can you share how you solved your problem?

**Comment by AO-IO** [comment]
> Hi yoyosan,
> 
> After I read carefully on readme is solve my problem...
> Sorry about that.
> 
> Thanks...

Can you please tell us how you solved it?

**Comment by yoyosan** [comment]
@AO-IO can you describe your problem?
