### ISSUE TITLE
Why laravel-ui and not fortify

### ISSUE THREAD

**Issue by bernhardh** [training-yoyosan/example-backend#3]
Why are you using the `laravel/ui` package, when we don't need the UI stuff? Why not https://laravel.com/docs/8.x/fortify ?

Btw. thank you for these 2 example-repos

**Comment by yoyosan** [comment]
> Why are you using the laravel/ui package, when we don't need the UI stuff? Why not https://laravel.com/docs/8.x/fortify ?

That's a great suggestion. I'll switch to that asap.

> Btw. thank you for these 2 example-repos

You're welcome.


LE: Switched to Laravel Fortify
